minetest.register_alias("bakedclay:dark_green","rainbow:render_green")
minetest.register_alias("bakedclay:dark_grey","rainbow:render_darkgrey")
minetest.register_alias("bakedclay:magenta","rainbow:render_magenta")
minetest.register_alias("bakedclay:pink","rainbow:render_pink")
minetest.register_alias("bakedclay:red","rainbow:render_red")
minetest.register_alias("bakedclay:yellow","rainbow:render_yellow")
minetest.register_alias("bakedclay:black","rainbow:render_black")
minetest.register_alias("bakedclay:blue","rainbow:render_blue")
minetest.register_alias("bakedclay:grey","rainbow:render_grey")

minetest.register_alias("bakedclay:slab_black_2","rainbow:slab_render_black_2")
minetest.register_alias("bakedclay:slab_black_quarter","rainbow:slab_black_quarter")
minetest.register_alias("bakedclay:slab_black","rainbow:slab_render_black")
minetest.register_alias("bakedclay:slab_grey","rainbow:slab_render_grey")
minetest.register_alias("bakedclay:slab_white","rainbow:slab_render_white")
minetest.register_alias("bakedclay:stair_white","rainbow:stair_render_white")
minetest.register_alias("bakedclay:white","rainbow:render_white")

minetest.register_alias("bakedclay:panel_white","rainbow:micro_render_white")
minetest.register_alias("bakedclay:panel_white_14","rainbow:panel_render_white_14")
minetest.register_alias("bakedclay:stair_black","rainbow:stair_render_black")
