minetest.register_alias("technic:concrete","rainbow:stone_grey")
minetest.register_alias("technic:concrete_post","default:air")
minetest.register_alias("technic:micro_concrete_15","default:air")
minetest.register_alias("technic:panel_concrete","rainbow:slab_stone_grey_1")
minetest.register_alias("technic:slope_concrete","rainbow_slope_stone_grey")
minetest.register_alias("technic:slope_concrete_half","rainbow:slope_stone_grey_half")
minetest.register_alias("technic:slope_concrete_half_raised","rainbow:slope_stone_grey_half_raised")
minetest.register_alias("technic:stainless_steel_block","default:steelblock")
